import SupabaseProvider from "@/components/providers/supabase-provider";
import NavBar from "@/components/navBar/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <SupabaseProvider>
        <body className=" bg-slate-100">
            <Toaster />
          <NavBar />
          {children}
        </body>
      </SupabaseProvider>
    </html>
  );
}
